-- Create ITEM_MASTER table
CREATE TABLE ITEM_MASTER (
    ITEM_ID NUMBER PRIMARY KEY,
    ITEM_DESC VARCHAR2(255),
    DEPARTMENT_ID NUMBER,
    CLASS_ID NUMBER,
    CREATION_DATE DATE DEFAULT SYSDATE
);

-- Create INVENTORY_LOC table
CREATE TABLE INVENTORY_LOC (
    LOC_ID NUMBER,
    ITEM_ID NUMBER,
    STOCK_ON_HAND NUMBER,
    STOCK_IN_TRANSIT NUMBER,
    CONSTRAINT PK_INVENTORY PRIMARY KEY (LOC_ID, ITEM_ID),
    CONSTRAINT FK_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM_MASTER(ITEM_ID)
);

-- Create PRICE_CHANGE table
CREATE TABLE PRICE_CHANGE (
    ITEM_ID NUMBER,
    OLD_PRICE NUMBER(10,2),
    NEW_PRICE NUMBER(10,2),
    CHANGE_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_PRICE_CHANGE PRIMARY KEY (ITEM_ID, CHANGE_DATE),
    CONSTRAINT FK_PC_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM_MASTER(ITEM_ID)
);
