-- Insert sample data into ITEM_MASTER
INSERT INTO ITEM_MASTER (ITEM_ID, ITEM_DESC, DEPARTMENT_ID, CLASS_ID)
SELECT LEVEL, 'Item ' || LEVEL, MOD(LEVEL, 10)+1, MOD(LEVEL, 5)+1
FROM dual CONNECT BY LEVEL <= 10000;

-- Insert sample data into INVENTORY_LOC
INSERT INTO INVENTORY_LOC (LOC_ID, ITEM_ID, STOCK_ON_HAND, STOCK_IN_TRANSIT)
SELECT MOD(LEVEL, 100)+1, LEVEL, DBMS_RANDOM.VALUE(0, 100), DBMS_RANDOM.VALUE(0, 20)
FROM dual CONNECT BY LEVEL <= 10000;

-- Insert sample data into PRICE_CHANGE
INSERT INTO PRICE_CHANGE (ITEM_ID, OLD_PRICE, NEW_PRICE, CHANGE_DATE)
SELECT LEVEL, DBMS_RANDOM.VALUE(10, 100), DBMS_RANDOM.VALUE(100, 200), SYSDATE - DBMS_RANDOM.VALUE(0, 365)
FROM dual CONNECT BY LEVEL <= 5000;

COMMIT;
