-- Step 1: Create Indexes
CREATE INDEX IDX_ITEM_DEPT ON ITEM_MASTER (DEPARTMENT_ID);
CREATE INDEX IDX_INVENTORY_ITEM ON INVENTORY_LOC (ITEM_ID);

-- Step 2: Partition PRICE_CHANGE Table
CREATE TABLE PRICE_CHANGE_PART
PARTITION BY RANGE (CHANGE_DATE) (
    PARTITION p_2022 VALUES LESS THAN (TO_DATE('01-JAN-2023','DD-MON-YYYY')),
    PARTITION p_2023 VALUES LESS THAN (TO_DATE('01-JAN-2024','DD-MON-YYYY')),
    PARTITION p_max  VALUES LESS THAN (MAXVALUE)
) AS
SELECT * FROM PRICE_CHANGE;

-- Step 3: Gather Schema Statistics
BEGIN
    DBMS_STATS.GATHER_SCHEMA_STATS(ownname => 'YOUR_SCHEMA_NAME');
END;
/
